import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams, ViewController, AlertController, ToastController } from 'ionic-angular';
import _ from 'lodash';
import { Alimento, AlimentosProvider } from '../../providers/alimentos/alimentos';

@IonicPage()
@Component({
  selector: 'page-pesquisar',
  templateUrl: 'pesquisar.html',
})

export class PesquisarPage {
  alimentos: Array<{nome: string; unidade: string; carbs: number}>;
  allAlimentos: any;
  queryText: string;
  model: Alimento;

  constructor(public navCtrl: NavController, 
              public navParams: NavParams, 
              public viewCtrl: ViewController,
              private alimentosProvider: AlimentosProvider,
              private alertCtrl: AlertController,
              private toastCtrl: ToastController) {
                
    this.queryText = '';
    this.inicializarAlimentos();

    this.allAlimentos = this.alimentos;
  }

  selecionaAlimento(alimento: any) {
    this.presentPrompt(alimento);
  }

  presentPrompt(alimento: any) {
    let alert = this.alertCtrl.create({
      title: 'Quantos(as) ' + alimento.unidade + '?',
      inputs: [
        {
          name: 'unit',
          placeholder: 'quantidade de ' + alimento.unidade,
          type: 'number'
        }
      ],
      buttons: [
        {
          text: 'Cancelar',
          role: 'cancel',
        },
        {
          text: 'OK',
          handler: data => {
            //montagem do objeto
            this.model = new Alimento();
            this.model.nome = alimento.nome;
            this.model.unidade = alimento.unidade;
            this.model.carbs = alimento.carbs;
            this.model.quantidade = data.unit;
            //fim do objeto
            this.alimentosProvider.insert(this.model);
            this.presentToast("Você acaba de comer " + alimento.nome + "!");
          }
        }
      ]
    });
    alert.present();
  }

  presentToast(mensagem) {
    let toast = this.toastCtrl.create({
      message: mensagem,
      duration: 3000
    });
    toast.present();
  }

  dismiss() {
    this.viewCtrl.dismiss();
  }

  filterAlimento(ali: any) {
    const val = ali.target.value;
      
    if (val && val.trim() != '') {
      this.alimentos = _.values(this.allAlimentos);
      this.alimentos = this.alimentos.filter((alimento) => {
        return (alimento.nome.toLowerCase().indexOf(val.toLowerCase()) > -1);
      })
    } else {
      this.alimentos = this.allAlimentos;
    }
  }
  

  inicializarAlimentos() {
    this.alimentos = [
      { nome: 'Abacate', unidade: '1/4 unidade pequena', carbs: 7 },
      { nome: 'Abacaxi', unidade: 'fatias médias', carbs: 9 },
      { nome: 'Abacaxi em calda', unidade: 'fatias médias', carbs: 22 },
      { nome: 'Abóbora moranga', unidade: 'colheres de sopa', carbs: 1 },
      { nome: 'Abobrinha', unidade: 'colheres de sopa', carbs: 1 },
      { nome: 'Abricó do Pará', unidade: 'fatias médias', carbs: 4 },
      { nome: 'Açaí', unidade: 'copos duplos', carbs: 72 },
      { nome: 'Açaí com banana, granola e mel', unidade: 'potes pequenos', carbs: 84 },
      { nome: 'Açaí (polpa)', unidade: 'taças pequenas', carbs: 57 },
      { nome: 'Acarajé', unidade: 'unidades médias', carbs: 22 },
      { nome: 'Acelga', unidade: 'pratos de sobremesa', carbs: 2 },
      { nome: 'Acerola', unidade: 'unidades pequenas', carbs: 1 },
      { nome: 'Achocolatado diet GOLD ®', unidade: 'colheres de sopa', carbs: 3 },
      { nome: 'Achocolatado diet Tal & Qual ®', unidade: 'colheres de sopa', carbs: 3 },
      { nome: 'Achocolatado (média)', unidade: 'colheres de sopa', carbs: 14 },
      { nome: 'Açúcar comum', unidade: 'colheres de sopa rasa', carbs: 15 },
      { nome: 'Açúcar mascavo', unidade: 'colheres de sopa rasa', carbs: 11 },
      { nome: 'Adoçante em pó Tal & Qual ®', unidade: 'colheres de sopa', carbs: 9 },
      { nome: 'Agrião', unidade: 'pratos cheios', carbs: 2 },
      { nome: 'Água de coco verde', unidade: 'copos duplos', carbs: 9 },
      { nome: 'Aguardente', unidade: 'doses', carbs: 0 },
      { nome: 'Aipim (mandioca)', unidade: 'pedaços pequenos', carbs: 13 },
      { nome: 'Alface', unidade: 'pratos sobremesa', carbs: 1 },
      { nome: 'Alfajor ®', unidade: 'unidades médias', carbs: 33 },
      { nome: 'Algodão doce', unidade: 'unidades', carbs: 15 },
      { nome: 'Alho', unidade: 'dentes pequenos', carbs: 0 },
      { nome: 'Alho poró', unidade: 'folhas', carbs: 1 },
      { nome: 'All Bran Original - Kelloggs ®', unidade: 'copo (20g Fibras)', carbs: 46 },
      { nome: 'Almeirão', unidade: 'pratos de sobremesa', carbs: 1 },
      { nome: 'Almôndega frita', unidade: 'unidades pequenas', carbs: 2 },
      { nome: 'Ambrosia', unidade: 'colheres de sopa rasa', carbs: 10 },
      { nome: 'Ameixa de queijo', unidade: 'unidades', carbs: 7 },
      { nome: 'Ameixa vermelha', unidade: 'unidades médias', carbs: 5 },
      { nome: 'Ameixa seca', unidade: 'unidades médias', carbs: 3 },
      { nome: 'Amêndoas', unidade: 'unidades pequenas', carbs: 0 },
      { nome: 'Amendocrem ®', unidade: 'colheres de sopa cheias', carbs: 8 },
      { nome: 'Amendoim', unidade: 'colheres de sopa', carbs: 3 },
      { nome: 'Amendoim caramelizado', unidade: 'pacotes pequenos', carbs: 15 },
      { nome: 'Amendoim japonês', unidade: 'colheres de sopa', carbs: 8 },
      { nome: 'Amido de milho', unidade: 'colheres de sopa cheias', carbs: 18 },
      { nome: 'Amora', unidade: '16 unidades médias', carbs: 13 },
      { nome: 'Angu', unidade: 'colheres de sopa', carbs: 4 },
      { nome: 'Arroz à grega', unidade: 'colheres de sopa', carbs: 7 },
      { nome: 'Arroz com lingüiça', unidade: 'colheres de sopa', carbs: 5 },
      { nome: 'Arroz com pequi', unidade: 'colheres de sopa', carbs: 7 },
      { nome: 'Arroz cozido', unidade: 'colheres de sopa', carbs: 5 },
      { nome: 'Arroz de carreteiro', unidade: 'colheres de sopa', carbs: 4 },
      { nome: 'Arroz doce', unidade: 'tacinhas de sobremesa', carbs: 33 },
      { nome: 'Arroz integral', unidade: 'colheres de sopa', carbs: 4 },
      { nome: 'Aspargos em conserva', unidade: 'unidades médias', carbs: 0 },
      { nome: 'Atum (cru)', unidade: 'filés médios', carbs: 0 },
      { nome: 'Atum em óleo', unidade: 'latas (drenado)', carbs: 0 },
      { nome: 'Atum ralado light', unidade: 'colheres de sopa cheias', carbs: 0 },
      { nome: 'Aveia em flocos', unidade: 'colheres de sopa', carbs: 9 },
      { nome: 'Azeite de dendê', unidade: 'colheres de sopa', carbs: 0 },
      { nome: 'Azeite de oliva', unidade: 'colheres de sopa', carbs: 0 },
      { nome: 'Azeitona', unidade: 'unidades', carbs: 0 },
      { nome: 'Baba de moça', unidade: 'colheres de sopa cheias', carbs: 26 },
      { nome: 'Bacalhoada', unidade: 'colheres de sopa', carbs: 2 },
      { nome: 'Bacon', unidade: 'fatias pequenas', carbs: 0 },
      { nome: 'Baconzitos ®', unidade: 'pacotes pequenos', carbs: 34 },
      { nome: 'Bacuri', unidade: 'filés médios', carbs: 6 },
      { nome: 'Baião de dois', unidade: 'escumadeiras', carbs: 53 },
      { nome: 'Bala de caramelo (média)', unidade: 'unidades', carbs: 4 },
      { nome: 'Bala de goma', unidade: 'unidades', carbs: 4 },
      { nome: 'Bala de jenipapo', unidade: 'unidades', carbs: 6 },
      { nome: 'Bala diet Solano ®', unidade: 'unidades', carbs: 3 },
      { nome: 'Bala Freegels ®', unidade: 'unidades', carbs: 4 },
      { nome: 'Bala Halls ®', unidade: 'unidades', carbs: 4 },
      { nome: 'Bala Mentex ®', unidade: 'unidades', carbs: 3 },
      { nome: 'Banana', unidade: 'unidades médias', carbs: 13 },
      { nome: 'Banana à milanesa', unidade: 'unidades médias', carbs: 24 },
      { nome: 'Banana caramelada', unidade: 'unidades médias', carbs: 59 },
      { nome: 'Banana flambada', unidade: 'unidades médias', carbs: 31 },
      { nome: 'Bananada', unidade: 'unidades médias', carbs: 27 },
      { nome: 'Bananada diet', unidade: 'fatias médias', carbs: 15 },
      { nome: 'Bananinha', unidade: 'unidades', carbs: 14 },
      { nome: 'Bananinha diet', unidade: 'tabletes', carbs: 29 },
      { nome: 'Banha de porco', unidade: 'colheres de chá', carbs: 0 },
      { nome: 'Barra de cereais (média)', unidade: 'unidades', carbs: 18 },
      { nome: 'Barra de cereais diet (média)', unidade: 'unidades', carbs: 15 },
      { nome: 'Barra de cereais light (média)', unidade: 'unidades', carbs: 16 },
      { nome: 'Batata barôa', unidade: 'colheres de sopa', carbs: 9 },
      { nome: 'Batata Chips Ruffles ®', unidade: 'pacotes pequenos', carbs: 25 },
      { nome: 'Batata doce', unidade: 'colheres de sopa', carbs: 7 },
      { nome: 'Batata inglesa cozida', unidade: 'colheres de sopa', carbs: 6 },
      { nome: 'Batata inglesa frita', unidade: 'colheres de sopa', carbs: 5 },
      { nome: 'Batata palha', unidade: 'colheres de sopa', carbs: 2 },
      { nome: 'Batata Pringles®', unidade: '12 unidades', carbs: 12 },
      { nome: 'Batida de fruta', unidade: 'tacinhas', carbs: 26 },
      { nome: 'Baton (chocolate) ®', unidade: 'unidades', carbs: 18 },
      { nome: 'Bebida energética Red Bull ®', unidade: 'latas', carbs: 28 },
      { nome: 'Energético sugar free Red Bull ®', unidade: 'latas', carbs: 2 },
      { nome: 'Beijinho', unidade: 'unidades pequenas', carbs: 3 },
      { nome: 'Beiju', unidade: 'unidades', carbs: 42 },
      { nome: 'Beirute de frango', unidade: 'unidades', carbs: 34 },
      { nome: 'Berinjela', unidade: 'fatias médias', carbs: 1 },
      { nome: 'Beterraba', unidade: 'colheres de sopa', carbs: 1 },
      { nome: 'Bife à milanesa', unidade: 'unidades', carbs: 11 },
      { nome: 'Bife frito (média)', unidade: 'unidades', carbs: 0 },
      { nome: 'Bife grelhado (média)', unidade: 'unidades médias', carbs: 0 },
      { nome: 'Bife à parmegiana', unidade: 'unidades pequenas', carbs: 8 },
      { nome: 'Big Mac - Mc Donald´s ®', unidade: 'unidades', carbs: 45 },
      { nome: 'Big Tasty - Mc Donald´s ®', unidade: 'unidades', carbs: 43 },
      { nome: 'Biscoitão de polvilho', unidade: 'unidades', carbs: 14 },
      { nome: 'Biscoito água', unidade: 'unidades', carbs: 3 },
      { nome: 'Biscoito água e sal', unidade: 'unidades', carbs: 5 },
      { nome: 'Biscoito amanteigado', unidade: 'unidades', carbs: 3 },
      { nome: 'Biscoito champanhe', unidade: 'unidades', carbs: 6 },
      { nome: 'Biscoito cream cracker', unidade: 'unidades', carbs: 5 },
      { nome: 'Biscoito de leite', unidade: 'unidades', carbs: 4 },
      { nome: 'Biscoito de leite diet', unidade: 'unidades pequenas', carbs: 2 },
      { nome: 'Biscoito de maisena', unidade: 'unidades', carbs: 4 },
      { nome: 'Biscoito de polvilho', unidade: 'unidades', carbs: 2 },
      { nome: 'Biscoito de queijo', unidade: 'unidades', carbs: 6 },
      { nome: 'Biscoito frito salgado', unidade: 'unidades', carbs: 9 },
      { nome: 'Biscoito maria', unidade: 'unidades', carbs: 4 },
      { nome: 'Biscoito recheado', unidade: 'unidades', carbs: 9 },
      { nome: 'Biscoito recheado diet', unidade: 'unidades pequenas', carbs: 8 },
      { nome: 'Biscoito Salpet®', unidade: 'unidades', carbs: 2 },
      { nome: 'Biscoito Sequilhos®', unidade: 'unidades pequenas', carbs: 2 },
      { nome: 'Biscoito tipo Club Social® (média)', unidade: 'pacotinhos', carbs: 18 },
      { nome: 'Biscoito tipo cookies (média)', unidade: 'unidades', carbs: 7 },
      { nome: 'Biscoito tipo cookies diet', unidade: 'unidades', carbs: 7 },
      { nome: 'Biscoito waffer', unidade: 'unidades', carbs: 5 },
      { nome: 'Biscoito waffer diet', unidade: 'unidades', carbs: 4 },
      { nome: 'Bisnaguinha', unidade: 'unidades', carbs: 11 },
      { nome: 'Blanquet de peru', unidade: 'fatias pequenas', carbs: 0 },
      { nome: 'Bobó de camarão', unidade: 'colheres de sopa', carbs: 6 },
      { nome: 'Bolacha de nata', unidade: 'unidades', carbs: 9 },
      { nome: 'Bolinha de queijo', unidade: 'unidades pequenas', carbs: 3 },
      { nome: 'Bolinho de aipim com carne seca', unidade: 'unidades médias', carbs: 12 },
      { nome: 'Bolinho de aipim com coco', unidade: 'fatias pequenas', carbs: 21 },
      { nome: 'Bolinho de arroz', unidade: 'unidades médias', carbs: 20 },
      { nome: 'Bolinho de bacalhau', unidade: 'unidades pequenas', carbs: 2 },
      { nome: 'Bolinho de chuva', unidade: 'unidades pequenas', carbs: 8 },
      { nome: 'Bolo de festa (recheio/ cobertura)', unidade: 'fatias médias', carbs: 54 },
      { nome: 'Bolo de festa diet', unidade: 'fatias médias', carbs: 20 },
      { nome: 'Bolo de milho verde', unidade: 'fatias', carbs: 30 },
      { nome: 'Bolo podre', unidade: 'fatias médias', carbs: 66 },
      { nome: 'Bolo simples sem cobertura', unidade: 'fatias médias', carbs: 21 },
      { nome: 'Bolo simples sem cobertura diet', unidade: 'fatias médias', carbs: 14 },
      { nome: 'Bolo recheado light Suavipan ®', unidade: 'unidades', carbs: 18 },
      { nome: 'Bomba de chocolate', unidade: 'unidades pequenas', carbs: 4 },
      { nome: 'Bombom Alpino ®', unidade: 'unidades', carbs: 8 },
      { nome: 'Bombom Amandita - Lacta ®', unidade: 'unidades', carbs: 5 },
      { nome: 'Bombom Chokito ®', unidade: 'unidades', carbs: 24 },
      { nome: 'Bombom Ouro Branco ®', unidade: 'unidades', carbs: 13 },
      { nome: 'Bombom Sonho de Valsa ®', unidade: 'unidades', carbs: 14 },
      { nome: 'Brigadeiro', unidade: 'unidades pequenas', carbs: 6 },
      { nome: 'Brigadeiro diet', unidade: 'unidades pequenas', carbs: 4 },
      { nome: 'Broa de amendoin', unidade: 'fatias médias', carbs: 21 },
      { nome: 'Broa de fubá', unidade: 'fatias médias', carbs: 30 },
      { nome: 'Brócolis', unidade: 'colheres de sopa', carbs: 0 },
      { nome: 'Buchada de bode', unidade: 'porções', carbs: 5 },
      { nome: 'Cacau em pó', unidade: 'colheres de sopa', carbs: 7 },
      { nome: 'Cachorro quente simples', unidade: 'unidades', carbs: 29 },
      { nome: 'Café com açúcar', unidade: 'xícaras de café', carbs: 2 },
      { nome: 'Café sem açúcar', unidade: 'xícaras de café', carbs: 0 },
      { nome: 'Caipirinha', unidade: 'doses', carbs: 27 },
      { nome: 'Cajá umbu', unidade: 'unidades pequenas', carbs: 2 },
      { nome: 'Caju', unidade: 'unidades médias', carbs: 14 },
      { nome: 'Cajuzinho', unidade: 'unidades pequenas', carbs: 6 },
      { nome: 'Calda de caramelo', unidade: 'colheres de sopa', carbs: 7 },
      { nome: 'Calda de chocolate', unidade: 'colheres de sopa', carbs: 5 },
      { nome: 'Calda de morango', unidade: 'colheres de sopa', carbs: 7 },
      { nome: 'Caldo de cana', unidade: 'copos duplos', carbs: 49 },
      { nome: 'Caldo de carne Knorr ®', unidade: 'tabletes', carbs: 1 },
      { nome: 'Caldo de feijão', unidade: 'conchas médias', carbs: 16 },
      { nome: 'Caldo de mandioca', unidade: 'conchas médias', carbs: 21 },
      { nome: 'Caldo verde', unidade: 'conchas médias', carbs: 7 },
      { nome: 'Camarão frito', unidade: 'colheres de sopa (4 und)', carbs: 0 },
      { nome: 'Camu camu', unidade: 'unidades', carbs: 0 },
      { nome: 'Canelone à bolonhesa', unidade: 'unidades médias', carbs: 5 },
      { nome: 'Canja de galinha', unidade: 'conchas médias', carbs: 12 },
      { nome: 'Canjica', unidade: 'conchas médias', carbs: 23 },
      { nome: 'Canjica diet', unidade: 'conchas médias', carbs: 13 },
      { nome: 'Capuccino em pó', unidade: 'colheres de sopa', carbs: 7 },
      { nome: 'Capuccino em pó chocolate', unidade: 'colheres de sopa', carbs: 7 },
      { nome: 'Capuccino em pó diet', unidade: 'colheres de sopa', carbs: 3 },
      { nome: 'Capuccino em pó light', unidade: 'colheres de sopa', carbs: 4 },
      { nome: 'Caqui', unidade: 'unidades pequenas', carbs: 17 },
      { nome: 'Carpaccio de carne', unidade: 'fatias médias', carbs: 0 },
      { nome: 'Cará cozido', unidade: 'colheres de sopa', carbs: 7 },
      { nome: 'Carambola', unidade: 'unidades e meia', carbs: 8 },
      { nome: 'Caramelo diet Hué ®', unidade: 'unidades', carbs: 4 },
      { nome: 'Caranguejada', unidade: 'conchas pequena', carbs: 3 },
      { nome: 'Caranguejo', unidade: 'unidades médias', carbs: 0 },
      { nome: 'Carbup Gel ®', unidade: 'sachês', carbs: 17 },
      { nome: 'Carne assada', unidade: 'fatias pequenas', carbs: 0 },
      { nome: 'Carne cozida', unidade: 'colheres de sopa', carbs: 0 },
      { nome: 'Carne de frango cozida', unidade: 'pedaços', carbs: 0 },
      { nome: 'Carne moída', unidade: 'colheres de sopa', carbs: 0 },
      { nome: 'Carpaccio de carne', unidade: 'fatias médias', carbs: 0 },
      { nome: 'Caruru', unidade: 'colheres de sopa', carbs: 2 },
      { nome: 'Castanha de caju', unidade: 'unidades pequenas', carbs: 1 },
      { nome: 'Castanha do Pará', unidade: 'unidades', carbs: 1 },
      { nome: 'Casulo de queijo', unidade: 'unidades festa', carbs: 3 },
      { nome: 'Catchup®', unidade: 'colheres de sopa', carbs: 3 },
      { nome: 'Catupiry ®', unidade: 'fatias médias', carbs: 1 },
      { nome: 'Caviar', unidade: 'porções', carbs: 4 },
      { nome: 'Cebola', unidade: 'colheres de sopa', carbs: 1 },
      { nome: 'Cenoura', unidade: 'colheres de sopa', carbs: 1 },
      { nome: 'Cereais diet', unidade: 'xícaras média', carbs: 22 },
      { nome: 'Cereais', unidade: 'xícaras média', carbs: 33 },
      { nome: 'Cereja', unidade: 'unidades médias', carbs: 1 },
      { nome: 'Cerveja', unidade: 'latas', carbs: 12 },
      { nome: 'Cerveja Bock ®', unidade: 'latas', carbs: 13 },
      { nome: 'Cerveja sem álcool', unidade: 'latas', carbs: 15 },
      { nome: 'Chá com limão ®', unidade: 'copos duplos', carbs: 22 },
      { nome: 'Chá sem açúcar', unidade: 'xícaras', carbs: 0 },
      { nome: 'Champignon em conserva', unidade: 'colheres de sopa', carbs: 0 },
      { nome: 'Chandelle chocolate ®', unidade: 'copinhos', carbs: 23 },
      { nome: 'Chantilly', unidade: 'colheres de sopa', carbs: 3 },
      { nome: 'Charuto de folhas de uva', unidade: 'unidades', carbs: 1 },
      { nome: 'Charuto de repolho', unidade: 'unidades', carbs: 1 },
      { nome: 'Cheeseburger', unidade: 'unidades', carbs: 40 },
      { nome: 'Cheetos ®', unidade: 'pacotes pequenos', carbs: 37 },
      { nome: 'Chiclete Bubbaloo ®', unidade: 'unidades', carbs: 4 },
      { nome: 'Chiclete de hortelã', unidade: 'unidades', carbs: 3 },
      { nome: 'Chiclete Trident ®', unidade: 'unidades', carbs: 1 },
      { nome: 'Chicória', unidade: 'colheres de sopa', carbs: 1 },
      { nome: 'Chimarrão', unidade: 'cuias médias', carbs: 0 },
      { nome: 'Chocolate ao leite', unidade: 'barras pequenas', carbs: 18 },
      { nome: 'Chocolate ao leite diet', unidade: 'barras pequenas', carbs: 13 },
      { nome: 'Chocolate Baton ®', unidade: 'unidades', carbs: 10 },
      { nome: 'Chocolate Bis ®', unidade: 'unidades', carbs: 5 },
      { nome: 'Chocolate com castanha', unidade: 'barras pequenas', carbs: 16 },
      { nome: 'Chocolate Diamante Negro ®', unidade: 'barras pequenas', carbs: 19 },
      { nome: 'Chocolate Galak ®', unidade: 'barras pequenas', carbs: 15 },
      { nome: 'Chocolate Talento ®', unidade: 'barras médias', carbs: 52 },
      { nome: 'Chocolate Talento ®', unidade: 'barrinhas', carbs: 13 },
      { nome: 'Chocolate Talento diet ®', unidade: 'barrinhas', carbs: 12 },
      { nome: 'Chocotone ®', unidade: 'fatias grandes', carbs: 33 },
      { nome: 'Chocotone diet ®', unidade: 'fatias grandes', carbs: 26 },
      { nome: 'Chope', unidade: 'tulipas', carbs: 11 },
      { nome: 'Chuchu', unidade: 'colheres de sopa', carbs: 1 },
      { nome: 'Chucrute', unidade: 'colheres de sopa', carbs: 0 },
      { nome: 'Churros com doce de leite', unidade: 'unidades', carbs: 44 },
      { nome: 'Cidra', unidade: 'unidades médias', carbs: 6 },
      { nome: 'Clara de ovo', unidade: 'unidades', carbs: 0 },
      { nome: 'Coalhada desnatada', unidade: 'copos', carbs: 8 },
      { nome: 'Coalhada integral', unidade: 'copos', carbs: 21 },
      { nome: 'Coca Cola ®', unidade: 'copos duplos', carbs: 24 },
      { nome: 'Coca Cola light / zero ®', unidade: 'copos duplos', carbs: 0 },
      { nome: 'Cocada', unidade: 'unidades pequenas', carbs: 28 },
      { nome: 'Cocada diet', unidade: 'tabletes', carbs: 10 },
      { nome: 'Coco da Bahia', unidade: 'pedaços médios', carbs: 6 },
      { nome: 'Coco ralado industrializado', unidade: 'colheres de sopa', carbs: 1 },
      { nome: 'Cogumelo em conserva', unidade: 'colheres de sopa', carbs: 0 },
      { nome: 'Cogumelo seco shitake', unidade: 'colheres de sopa', carbs: 11 },
      { nome: 'Colomba pascoal', unidade: 'fatias médias', carbs: 22 },
      { nome: 'Conhaque', unidade: 'copos', carbs: 0 },
      { nome: 'Coquetel com run e suco de lima (daiquiri)', unidade: 'copos', carbs: 26 },
      { nome: 'Corn Flakes - Kellogg´s ®', unidade: 'xícaras', carbs: 24 },
      { nome: 'Costela de boi assada', unidade: 'pedaços pequenos', carbs: 0 },
      { nome: 'Costelinha de porco', unidade: 'unidades médias', carbs: 0 },
      { nome: 'Couve', unidade: 'folhas médias', carbs: 2 },
      { nome: 'Couve-flor', unidade: 'colheres de sopa', carbs: 1 },
      { nome: 'Coxinha de frango (festa)', unidade: 'unidades (festa)', carbs: 4 },
      { nome: 'Coxinha de frango', unidade: 'unidades médias', carbs: 21 },
      { nome: 'Cream cheese', unidade: 'colheres de sobremesa', carbs: 0 },
      { nome: 'Creme de abacate com açúcar', unidade: 'copos', carbs: 22 },
      { nome: 'Creme de arroz/milho cozido', unidade: 'colheres de sopa', carbs: 4 },
      { nome: 'Creme de baun./choco/coco/caramelo', unidade: 'colheres de sopa', carbs: 7 },
      { nome: 'Creme de leite', unidade: 'colheres de sopa', carbs: 0 },
      { nome: 'Creme de leite light', unidade: 'colheres de sopa', carbs: 0 },
      { nome: 'Cremogema Tradicional ®', unidade: 'colheres de sopa', carbs: 18 },
      { nome: 'Cremutcho ®', unidade: 'colheres de sopa', carbs: 0 },
      { nome: 'Crepe de maçã diet', unidade: 'unidades', carbs: 76 },
      { nome: 'Croissant', unidade: 'unidades médias', carbs: 18 },
      { nome: 'Croquete de carne', unidade: 'unidades médias', carbs: 9 },
      { nome: 'Cup Noodles ®', unidade: 'unidades comerciais', carbs: 38 },
      { nome: 'Cupuaçu', unidade: 'conchas médias', carbs: 18 },
      { nome: 'Cural', unidade: 'colheres de sopa cheias', carbs: 6 },
      { nome: 'Cuscuz de milho com leite', unidade: 'pedaços pequenos', carbs: 36 },
      { nome: 'Damasco seco', unidade: 'unidades médias', carbs: 4 },
      { nome: 'Danette chocolate ®', unidade: 'copinhos', carbs: 25 },
      { nome: 'Danoninho ®', unidade: 'potinho', carbs: 8 },
      { nome: 'Diet Shake ®', unidade: 'porções', carbs: 21 },
      { nome: 'Dobradinha', unidade: 'colheres de sopa', carbs: 3 },
      { nome: 'Doce de abóbora', unidade: 'colheres de sopa cheias', carbs: 18 },
      { nome: 'Doce de banana em calda', unidade: 'colheres de sopa cheias', carbs: 9 },
      { nome: 'Doce de cidra', unidade: 'colheres de sopa', carbs: 20 },
      { nome: 'Doce de laranja azeda', unidade: '1/2 unidade grande', carbs: 42 },
      { nome: 'Doce de leite', unidade: 'colheres de sopa cheias', carbs: 22 },
      { nome: 'Doce de leite diet', unidade: 'colheres de sopa cheias', carbs: 16 },
      { nome: 'Doce de leite com coco diet', unidade: 'fatias pequenas', carbs: 10 },
      { nome: 'Doce de mamão verde', unidade: 'colheres de sopa cheias', carbs: 19 },
      { nome: 'Doce de mamão diet', unidade: 'colheres de sopa', carbs: 3 },
      { nome: 'Doritos ®', unidade: 'pacotes pequenos', carbs: 31 },
      { nome: 'Empada', unidade: 'unidades médias', carbs: 19 },
      { nome: 'Empada (festa)', unidade: 'unidades festa', carbs: 4 },
      { nome: 'Empadão', unidade: 'fatias médias', carbs: 37 },
      { nome: 'Enroladinho de salsicha', unidade: 'unidades festa', carbs: 2 },
      { nome: 'Ervilha enlatada', unidade: 'colheres de sopa', carbs: 6 },
      { nome: 'Ervilha vagem cozida', unidade: 'colheres de sopa', carbs: 4 },
      { nome: 'Escarola', unidade: 'pratos rasos', carbs: 3 },
      { nome: 'Esfiha (média)', unidade: 'unidades médias', carbs: 29 },
      { nome: 'Esfiha (festa)', unidade: 'unidades festa', carbs: 4 },
      { nome: 'Esfiha aberta', unidade: 'unidades médias', carbs: 11 },
      { nome: 'Espinafre', unidade: 'colheres de sopa', carbs: 1 },
      { nome: 'Estrogonofe de Carne / Frango', unidade: 'Colheres de Sopa', carbs: 0 },
      { nome: 'Fandangos ®', unidade: 'pacotes pequenos', carbs: 41 },
      { nome: 'Fanta Laranja ®', unidade: 'copos duplos', carbs: 35 },
      { nome: 'Fanta Laranja diet ®', unidade: 'copos duplos ', carbs: 0 },
      { nome: 'Farelo de aveia', unidade: 'colheres de sopa', carbs: 4 },
      { nome: 'Farelo de trigo', unidade: 'colheres de sopa', carbs: 12 },
      { nome: 'Farinha de mandioca', unidade: 'colheres de sopa', carbs: 14 },
      { nome: 'Farinha de milho', unidade: 'colheres de sopa', carbs: 12 },
      { nome: 'Farinha de rosca', unidade: 'colheres de sopa cheias', carbs: 11 },
      { nome: 'Farinha de soja', unidade: 'colheres de sopa cheias', carbs: 5 },
      { nome: 'Farinha de trigo', unidade: 'colheres de sopa', carbs: 16 },
      { nome: 'Farinha Láctea ®', unidade: 'colheres de sopa cheias', carbs: 15 },
      { nome: 'Farofa', unidade: 'colheres de sopa', carbs: 12 },
      { nome: 'Farofa com lingüiça', unidade: 'colheres de sopa cheias', carbs: 7 },
      { nome: 'Fécula de batata', unidade: 'colheres de sopa cheias', carbs: 16 },
      { nome: 'Feijão comum', unidade: 'colheres de sopa', carbs: 3 },
      { nome: 'Feijão tropeiro', unidade: 'colheres de sopa', carbs: 7 },
      { nome: 'Feijoada caseira', unidade: 'conchas médias', carbs: 24 },
      { nome: 'Figo em calda', unidade: 'unidades pequenas', carbs: 13 },
      { nome: 'Figo em calda diet', unidade: 'unidades pequenas', carbs: 2 },
      { nome: 'Figo fresco', unidade: 'unidades grandes', carbs: 13 },
      { nome: 'Flan Baunilha', unidade: 'potinhos', carbs: 15 },
      { nome: 'Flan Baunilha diet', unidade: 'potinhos', carbs: 8 },
      { nome: 'Fondue de chocolate', unidade: 'colheres de sobremesa', carbs: 5 },
      { nome: 'Fondue de queijo', unidade: 'colheres de sobremesa', carbs: 1 },
      { nome: 'Framboesa', unidade: 'unidades médias', carbs: 2 },
      { nome: 'Fruta do conde', unidade: 'unidades médias', carbs: 15 },
      { nome: 'Frutas cristalizadas', unidade: 'colheres de sopa', carbs: 16 },
      { nome: 'Fubá', unidade: 'colheres de sopa', carbs: 15 },
      { nome: 'Funghi', unidade: 'colheres de sopa cheias', carbs: 10 },
      { nome: 'Galinhada com pequi', unidade: 'colheres de sopa', carbs: 5 },
      { nome: 'Gatorade ®', unidade: 'copos', carbs: 12 },
      { nome: 'Gelatina (média)', unidade: 'potinhos', carbs: 13 },
      { nome: 'Gelatina diet (média)', unidade: 'potinhos', carbs: 0 },
      { nome: 'Geléia de mocotó', unidade: 'colheres de sopa cheias', carbs: 14 },
      { nome: 'Geléia diet (média)', unidade: 'pontas de faca', carbs: 1 },
      { nome: 'Geléia (média)', unidade: 'pontas de faca', carbs: 4 },
      { nome: 'Gema de ovo', unidade: 'unidades', carbs: 0 },
      { nome: 'Gemada', unidade: 'colheres de sopa', carbs: 5 },
      { nome: 'Gim', unidade: 'doses', carbs: 22 },
      { nome: 'Glucose de milho', unidade: 'colheres de sopa cheias', carbs: 11 },
      { nome: 'Goiaba', unidade: 'unidades médias', carbs: 12 },
      { nome: 'Goiabada', unidade: 'fatias pequenas', carbs: 26 },
      { nome: 'Goiabada diet', unidade: 'fatias pequenas', carbs: 5 },
      { nome: 'Granola sem açúcar', unidade: 'colheres de sopa', carbs: 8 },
      { nome: 'Grão de bico', unidade: 'colheres de sopa', carbs: 6 },
      { nome: 'Guariroba', unidade: 'colheres de sopa', carbs: 1 },
      { nome: 'Hambúrguer', unidade: 'unidades', carbs: 0 },
      { nome: 'Inhame', unidade: 'colheres de sopa', carbs: 6 },
      { nome: 'Iogurte Actívia®', unidade: 'potinhos', carbs: 16 },
      { nome: 'Iogurte Actívia light®', unidade: 'potinhos', carbs: 11 },
      { nome: 'Iogurte Actívia Natural®', unidade: 'potes', carbs: 12 },
      { nome: 'Iogurte com mel', unidade: 'potinhos', carbs: 15 },
      { nome: 'Iogurte Corpus light®', unidade: 'potinhos', carbs: 7 },
      { nome: 'Iogurte Corpus light®', unidade: 'garrafinhas', carbs: 10 },
      { nome: 'Iogurte Dan up®', unidade: 'garrafinhas', carbs: 28 },
      { nome: 'Iogurte de frutas (média)', unidade: 'potinhos', carbs: 17 },
      { nome: 'Iogurte de frutas diet (média)', unidade: 'potinhos', carbs: 7 },
      { nome: 'Iogurte fruta e cereal', unidade: 'potinhos', carbs: 18 },
      { nome: 'Iogurte natural desnatado', unidade: 'copos', carbs: 12 },
      { nome: 'Iogurte natural integral', unidade: 'copos', carbs: 10 },
      { nome: 'Isca de peixe frita', unidade: 'escumadeiras', carbs: 16 },
      { nome: 'Jabuticaba', unidade: '10 unidades', carbs: 5 },
      { nome: 'Jaca', unidade: 'bago médio', carbs: 3 },
      { nome: 'Jambo', unidade: 'unidades médias', carbs: 5 },
      { nome: 'Jenipapo', unidade: 'unidades pequenas', carbs: 46 },
      { nome: 'Jiló', unidade: 'colheres de sopa', carbs: 2 },
      { nome: 'Kani Kama (cru)', unidade: 'unidades', carbs: 0 },
      { nome: 'Ketchup', unidade: 'colheres de sopa', carbs: 1 },
      { nome: 'Kibe frito', unidade: 'unidades médias', carbs: 11 },
      { nome: 'Kibe frito (festa)', unidade: 'unidades festa', carbs: 3 },
      { nome: 'Kiwi', unidade: 'unidades médias', carbs: 11 },
      { nome: 'Laranja', unidade: 'unidades médias', carbs: 12 },
      { nome: 'Laranjada', unidade: 'copos duplos', carbs: 20 },
      { nome: 'Lasanha', unidade: 'colheres de sopa', carbs: 6 },
      { nome: 'Leite condensado', unidade: 'colheres de sopa', carbs: 8 },
      { nome: 'Leite condensado diet', unidade: 'colheres de sopa', carbs: 7 },
      { nome: 'Leite de coco Sococo ®', unidade: 'colheres de sopa', carbs: 0 },
      { nome: 'Leite de coco Sococo light ®', unidade: 'colheres de sopa', carbs: 0 },
      { nome: 'Leite de soja', unidade: 'copos duplos', carbs: 4 },
      { nome: 'Leite de soja Ades Original ®', unidade: 'copos', carbs: 7 },
      { nome: 'Leite de soja Ades Original light ®', unidade: 'copos', carbs: 1 },
      { nome: 'Leite de soja em pó', unidade: 'colheres de sopa', carbs: 6 },
      { nome: 'Leite de vaca desnatado', unidade: 'copos duplos', carbs: 12 },
      { nome: 'Leite de vaca integral', unidade: 'copos duplos', carbs: 12 },
      { nome: 'Leite de vaca semi-desnatado', unidade: 'copos duplos', carbs: 12 },
      { nome: 'Leite em pó desnatado', unidade: 'colheres de sopa', carbs: 5 },
      { nome: 'Leite em pó integral', unidade: 'colheres de sopa', carbs: 5 },
      { nome: 'Leite materno', unidade: 'copos', carbs: 14 },
      { nome: 'Lentilha', unidade: 'colheres de sopa', carbs: 4 },
      { nome: 'Licor', unidade: 'doses', carbs: 8 },
      { nome: 'Lima', unidade: 'unidades médias', carbs: 9 },
      { nome: 'Limonada sem açúcar', unidade: 'copos duplos', carbs: 4 },
      { nome: 'Lingüiça assada', unidade: 'gomos', carbs: 1 },
      { nome: 'Lingüiça calabresa', unidade: 'gomos', carbs: 2 },
      { nome: 'Lingüiça frita', unidade: 'gomos', carbs: 0 },
      { nome: 'Maçã', unidade: 'unidades pequenas', carbs: 12 },
      { nome: 'Macarrão alho e óleo', unidade: 'pegadores', carbs: 35 },
      { nome: 'Macarrão Nissin Miojo ®', unidade: 'pacotes comerciais', carbs: 42 },
      { nome: 'Macarronada', unidade: 'pegadores', carbs: 26 },
      { nome: 'Maionese', unidade: 'pontas de faca', carbs: 0 },
      { nome: 'Maionese de legumes', unidade: 'colheres de sopa cheias', carbs: 6 },
      { nome: 'Maionese light', unidade: 'pontas de faca', carbs: 0 },
      { nome: 'Mamão', unidade: 'fatias médias', carbs: 16 },
      { nome: 'Mandioca cozida', unidade: 'colheres de sopa rasa', carbs: 5 },
      { nome: 'Manga', unidade: 'unidades médias', carbs: 21 },
      { nome: 'Manjar Branco com ameixa em calda', unidade: 'porções', carbs: 30 },
      { nome: 'Manjar pronto - Royal ®', unidade: 'porções', carbs: 20 },
      { nome: 'Manteiga', unidade: 'pontas de faca', carbs: 0 },
      { nome: 'Maracujá', unidade: 'unidades médias', carbs: 10 },
      { nome: 'Margarina', unidade: 'pontas de faca', carbs: 0 },
      { nome: 'Margarina light', unidade: 'pontas de faca', carbs: 0 },
      { nome: 'Maria Mole - Nutrimental ®', unidade: 'porções', carbs: 29 },
      { nome: 'Marmelada', unidade: 'fatias pequenas em corte', carbs: 26 },
      { nome: 'Marron-glacê', unidade: 'fatias pequenas em corte', carbs: 26 },
      { nome: 'Marshmallow', unidade: 'colheres de sopa cheias', carbs: 27 },
      { nome: 'Martini', unidade: 'taças', carbs: 19 },
      { nome: 'Maxi Goiabinha®', unidade: 'unidades', carbs: 15 },
      { nome: 'Mc Casquinha ®', unidade: 'unidades', carbs: 30 },
      { nome: 'Mc Cheddar Mc Melt ®', unidade: 'unidades', carbs: 36 },
      { nome: 'Mc Cheeseburger ®', unidade: 'unidades', carbs: 31 },
      { nome: 'Mc Chicken ®', unidade: 'unidades', carbs: 44 },
      { nome: 'Mc Chicken Grill ®', unidade: 'unidades', carbs: 23 },
      { nome: 'Mc Chicken Mc Junior ®', unidade: 'unidades', carbs: 28 },
      { nome: 'Mc Choco Mac ®', unidade: 'unidades', carbs: 28 },
      { nome: 'Mc Colosso ®', unidade: 'unidades', carbs: 61 },
      { nome: 'Mc Crispy Chicken ®', unidade: 'unidades', carbs: 31 },
      { nome: 'Mc Duplo ®', unidade: 'unidades', carbs: 31 },
      { nome: 'Mc Fish ®', unidade: 'unidades', carbs: 41 },
      { nome: 'Mc Fritas grande ®', unidade: 'pacotes', carbs: 56 },
      { nome: 'Mc Fritas média ®', unidade: 'pacotes', carbs: 39 },
      { nome: 'Mc Fritas pequena ®', unidade: 'pacotes', carbs: 28 },
      { nome: 'Mc Hambúrguer ®', unidade: 'unidades', carbs: 30 },
      { nome: 'Mc Iogurte Parfait ®', unidade: 'unidades', carbs: 25 },
      { nome: 'Mc Mix M&M ®', unidade: 'unidades', carbs: 50 },
      { nome: 'Mc Nuggets ®', unidade: 'unidades', carbs: 2 },
      { nome: 'Mc Premium Salad ®', unidade: 'unidades', carbs: 12 },
      { nome: 'Mc Premium Salad Crispy ®', unidade: 'unidades', carbs: 21 },
      { nome: 'Mc Premium Salad Grill ®', unidade: 'unidades', carbs: 13 },
      { nome: 'Mc Quarteirão ®', unidade: 'unidades', carbs: 37 },
      { nome: 'Mc Queijo Quente ®', unidade: 'unidades', carbs: 29 },
      { nome: 'Mc Salad Burger Jr ®', unidade: 'unidades', carbs: 32 },
      { nome: 'Mc Shake (média) ®', unidade: 'unidades pequenas', carbs: 41 },
      { nome: 'Mc Shake (média) ®', unidade: 'unidades grandes', carbs: 67 },
      { nome: 'Mc Sundae chocolate ®', unidade: 'unidades', carbs: 46 },
      { nome: 'Mc Top Sundae chocolate ®', unidade: 'unidades', carbs: 65 },
      { nome: 'Mc Torta de banana ®', unidade: 'unidades', carbs: 32 },
      { nome: 'Mc Torta de maçã ®', unidade: 'unidades', carbs: 30 },
      { nome: 'Mel', unidade: 'colheres de sopa', carbs: 12 },
      { nome: 'Melancia', unidade: 'fatias médias', carbs: 12 },
      { nome: 'Melão', unidade: 'fatias grandes', carbs: 8 },
      { nome: 'Mexerica', unidade: 'unidades médias', carbs: 15 },
      { nome: 'Milharina ®', unidade: 'colheres de sopa', carbs: 15 },
      { nome: 'Milho verde - espiga', unidade: 'espigas grandes', carbs: 28 },
      { nome: 'Milho verde conserva', unidade: 'colheres de sopa', carbs: 4 },
      { nome: 'Milkshake (média)', unidade: 'copos', carbs: 55 },
      { nome: 'Mingau de aveia', unidade: 'colheres de sopa cheias', carbs: 5 },
      { nome: 'Mini Mc Salad Shaker ®', unidade: 'unidades', carbs: 3 },
      { nome: 'Mini pizza', unidade: 'unidades', carbs: 15 },
      { nome: 'Misto quente', unidade: 'unidades', carbs: 29 },
      { nome: 'Molho à bolonhesa', unidade: 'colheres de sopa', carbs: 1 },
      { nome: 'Molho branco', unidade: 'colheres de sopa', carbs: 3 },
      { nome: 'Molho de tomate', unidade: 'colheres de sopa', carbs: 1 },
      { nome: 'Molho inglês', unidade: 'colheres de sopa', carbs: 0 },
      { nome: 'Molho madeira', unidade: 'colheres de sopa', carbs: 1 },
      { nome: 'Molho shoyo', unidade: 'colheres de sopa', carbs: 0 },
      { nome: 'Molho vinagrete', unidade: 'colheres de sopa', carbs: 1 },
      { nome: 'Moqueca de peixe', unidade: 'porções', carbs: 3 },
      { nome: 'Morango', unidade: '8 unidades grandes', carbs: 11 },
      { nome: 'Mortadela', unidade: 'fatias médias', carbs: 0 },
      { nome: 'Mostarda', unidade: 'colheres de sopa', carbs: 0 },
      { nome: 'Mostarda - molho', unidade: 'sachês ou colheres de sopa', carbs: 0 },
      { nome: 'Mousse de chocolate', unidade: 'colheres de sopa', carbs: 8 },
      { nome: 'Mousse de maracujá', unidade: 'colheres de sopa', carbs: 11 },
      { nome: 'Mucilon de arroz ®', unidade: 'colheres de sopa', carbs: 8 },
      { nome: 'Mucilon de milho ®', unidade: 'colheres de sopa', carbs: 8 },
      { nome: 'Mugunzá', unidade: 'copos duplos', carbs: 63 },
      { nome: 'Muffin (média)', unidade: 'unidades', carbs: 17 },
      { nome: 'Musli ®', unidade: 'colheres de sopa', carbs: 11 },
      { nome: 'Nabo', unidade: 'colheres de sopa', carbs: 1 },
      { nome: 'NanNestlé ®', unidade: 'medidas', carbs: 2.5 },
      { nome: 'Nan 2 Nestlé ®', unidade: 'medidas', carbs: 2.5 },
      { nome: 'Nectarina', unidade: 'unidades médias', carbs: 12 },
      { nome: 'Nescau ®', unidade: 'colheres de sopa', carbs: 9 },
      { nome: 'Nescau Light ®', unidade: 'colheres de sopa', carbs: 7 },
      { nome: 'Nesfit ®', unidade: 'xícaras', carbs: 30 },
      { nome: 'Nesquik pó Nestlé ®', unidade: 'colheres de sopa', carbs: 13 },
      { nome: 'Nestlé Fibra +®', unidade: 'xícaras', carbs: 22 },
      { nome: 'Neston ®', unidade: 'colheres de sopa', carbs: 6 },
      { nome: 'Nhoque', unidade: 'colheres de sopa', carbs: 6 },
      { nome: 'Nhoque de batatas com molho', unidade: 'colheres de sopa', carbs: 6 },
      { nome: 'Niguiri sushi', unidade: 'unidade', carbs: 2 },
      { nome: 'Novomilk chocolate ® (pó)', unidade: 'colheres de sopa', carbs: 10 },
      { nome: 'Nozes', unidade: 'unidades', carbs: 1 },
      { nome: 'Nuggets ® (média)', unidade: 'unidades', carbs: 4 },
      { nome: 'Nutella ®', unidade: 'colheres de sopa', carbs: 11 },
      { nome: 'Óleo vegetal (média)', unidade: 'colheres de sobremesa', carbs: 0 },
      { nome: 'Omelete simples', unidade: 'unidades (ovo)', carbs: 0 },
      { nome: 'Ovo cozido', unidade: 'unidades', carbs: 0 },
      { nome: 'Ovo de codorna', unidade: 'unidades', carbs: 0 },
      { nome: 'Ovo de páscoa (média)', unidade: 'pedaços médios', carbs: 14 },
      { nome: 'Ovomaltine ®', unidade: 'colheres de sopa', carbs: 11 },
      { nome: 'Paçoquinha', unidade: 'unidade', carbs: 21 },
      { nome: 'Paçoquinha diet', unidade: 'unidade', carbs: 8 },
      { nome: 'Palmito', unidade: 'unidades médias', carbs: 4 },
      { nome: 'Pamonha', unidade: 'unidades grandes', carbs: 51 },
      { nome: 'Panetone (média)', unidade: 'fatias grandes', carbs: 33 },
      { nome: 'Panetone diet (média)', unidade: 'fatias grandes', carbs: 28 },
      { nome: 'Panqueca', unidade: 'unidades médias', carbs: 12 },
      { nome: 'Pão ciabatta', unidade: 'fatias grandes', carbs: 24 },
      { nome: 'Pão de batata', unidade: 'unidade', carbs: 29 },
      { nome: 'Pão de centeio', unidade: 'pedaços médios', carbs: 32 },
      { nome: 'Pão de forma', unidade: 'fatia', carbs: 17 },
      { nome: 'Pão de forma diet', unidade: 'fatia', carbs: 10 },
      { nome: 'Pão de forma integral', unidade: 'fatia', carbs: 11 },
      { nome: 'Pão de hambúrguer', unidade: 'unidade', carbs: 40 },
      { nome: 'Pão de leite', unidade: 'fatia', carbs: 11 },
      { nome: 'Pão de mel', unidade: 'unidades pequenas', carbs: 8 },
      { nome: 'Pão de mel com chocolate - Pan ®', unidade: 'unidade', carbs: 10 },
      { nome: 'Pão de queijo', unidade: 'unidades grandes', carbs: 14 },
      { nome: 'Pão de queijo', unidade: 'unidades pequenas', carbs: 4 },
      { nome: 'Pão francês', unidade: 'unidade', carbs: 28 },
      { nome: 'Pão francês sem miolo', unidade: 'unidade', carbs: 17 },
      { nome: 'Pão hot dog', unidade: 'unidade', carbs: 29 },
      { nome: 'Pão sírio', unidade: 'unidades médias', carbs: 33 },
      { nome: 'Pão sovado', unidade: 'fatias médias', carbs: 27 },
      { nome: 'Papinha de bebê doce (média)', unidade: 'potes', carbs: 33 },
      { nome: 'Papinha de bebê salgada (média)', unidade: 'potes', carbs: 12 },
      { nome: 'Pastel', unidade: 'unidades médias', carbs: 14 },
      { nome: 'Pastel (festa)', unidade: 'unidades pequenas', carbs: 3 },
      { nome: 'Patê (média)', unidade: 'colheres de chá', carbs: 0 },
      { nome: 'Pavê de amendoim', unidade: 'colheres de sopa cheias', carbs: 9 },
      { nome: 'Pavê de chocolate', unidade: 'colheres de sopa', carbs: 7 },
      { nome: 'Pavê de fruta', unidade: 'colheres de sopa', carbs: 7 },
      { nome: 'Pé de moleque', unidade: 'unidades médias', carbs: 14 },
      { nome: 'Pé de moleque diet Hué ®', unidade: 'tabletes', carbs: 13 },
      { nome: 'Peito de frango cozido', unidade: 'unidade', carbs: 0 },
      { nome: 'Peito de peru light', unidade: 'fatia', carbs: 0 },
      { nome: 'Peixe grelhado', unidade: 'posta oufilé', carbs: 0 },
      { nome: 'Pepino', unidade: 'unidades médias', carbs: 3 },
      { nome: 'Pequi', unidade: 'unidades médias', carbs: 1 },
      { nome: 'Pêra', unidade: 'unidades médias', carbs: 15 },
      { nome: 'Pêssego', unidade: 'unidades grandes', carbs: 12 },
      { nome: 'Pêssego em calda', unidade: 'metade', carbs: 12 },
      { nome: 'Pêssego em calda diet', unidade: 'metade', carbs: 3 },
      { nome: 'Picolé Chicabon ®', unidade: 'unidade', carbs: 19 },
      { nome: 'Picolé Chokito ®', unidade: 'unidade', carbs: 14 },
      { nome: 'Picolé de coco', unidade: 'unidade', carbs: 16 },
      { nome: 'Picolé de Fruta Kibon ®', unidade: 'unidade', carbs: 16 },
      { nome: 'Picolé de limão', unidade: 'unidade', carbs: 14 },
      { nome: 'Picolé Tablito ®', unidade: 'unidade', carbs: 17 },
      { nome: 'Pimentão', unidade: 'colheres de sopa', carbs: 0 },
      { nome: 'Pinga', unidade: 'doses', carbs: 0 },
      { nome: 'Pingo D´ouro - Elma Chips ®', unidade: 'pacotinhos', carbs: 18 },
      { nome: 'Pipoca doce', unidade: 'saco pequeno ouxícara', carbs: 15 },
      { nome: 'Pipoca doce industrializada', unidade: 'xícara', carbs: 17 },
      { nome: 'Pipoca salgada', unidade: 'saco pequeno ouxícara', carbs: 8 },
      { nome: 'Pirão', unidade: 'colheres de sopa', carbs: 9 },
      { nome: 'Pirulito', unidade: 'unidade', carbs: 19 },
      { nome: 'Pizza de calabresa', unidade: 'fatias grandes', carbs: 28 },
      { nome: 'Pizza de mussarela', unidade: 'fatias grandes', carbs: 28 },
      { nome: 'Pizza portuguesa', unidade: 'fatias grandes', carbs: 30 },
      { nome: 'Pizza (outros sabores)', unidade: 'fatias grandes', carbs: 28 },
      { nome: 'Polenta', unidade: 'colheres de sopa', carbs: 4 },
      { nome: 'Polpa de fruta acerola', unidade: 'saquinho', carbs: 7 },
      { nome: 'Polvilho', unidade: 'colheres de sopa', carbs: 13 },
      { nome: 'Presunto de peru', unidade: 'fatia', carbs: 0 },
      { nome: 'Presunto de porco', unidade: 'fatia', carbs: 0 },
      { nome: 'Presunto magro', unidade: 'fatia', carbs: 0 },
      { nome: 'Proteína texturizada de soja', unidade: 'colheres de sopa', carbs: 3 },
      { nome: 'Pudim industrializado', unidade: 'colheres de sopa', carbs: 7 },
      { nome: 'Pudim industrializado diet', unidade: 'colheres de sopa', carbs: 4 },
      { nome: 'Pudim leite condensado', unidade: 'colheres de sopa cheias', carbs: 17 },
      { nome: 'Purê de batatas', unidade: 'colheres de sopa', carbs: 4 },
      { nome: 'Queijo minas frescal', unidade: 'fatias médias', carbs: 0 },
      { nome: 'Queijo mussarela', unidade: 'fatia', carbs: 0 },
      { nome: 'Queijo prato', unidade: 'fatia', carbs: 0 },
      { nome: 'Queijo ricota', unidade: 'fatias grandes', carbs: 0 },
      { nome: 'Quentão com adoçante', unidade: 'copo', carbs: 3 },
      { nome: 'Quiabo', unidade: 'colheres de sopa', carbs: 1 },
      { nome: 'Quindim', unidade: 'unidades pequenas', carbs: 9 },
      { nome: 'Quinoa', unidade: 'colheres de sopa', carbs: 6 },
      { nome: 'Rabanada', unidade: 'unidades médias', carbs: 21 },
      { nome: 'Rabanete', unidade: 'unidades médias', carbs: 0 },
      { nome: 'Rapadura', unidade: 'pedaços pequenos', carbs: 28 },
      { nome: 'Ravióli de carne', unidade: 'escumadeiras', carbs: 25 },
      { nome: 'Refresco comum com açúcar', unidade: 'copos', carbs: 14 },
      { nome: 'Refresco diet (Clight®)', unidade: 'copos', carbs: 0 },
      { nome: 'Refrigerante comum (média)', unidade: 'copos', carbs: 22 },
      { nome: 'Refrigerante diet /light /zero (média)', unidade: 'copos', carbs: 0 },
      { nome: 'Repolho', unidade: 'colheres de sopa', carbs: 0 },
      { nome: 'Requeijão', unidade: 'colheres de sobremesa', carbs: 0 },
      { nome: 'Requeijão light', unidade: 'colheres de sobremesa', carbs: 0 },
      { nome: 'Risole', unidade: 'unidades médias', carbs: 10 },
      { nome: 'Risole de milho com caturpiry', unidade: 'unidades festa', carbs: 4 },
      { nome: 'Risoto de frango', unidade: 'colheres de sopa', carbs: 6 },
      { nome: 'Risoto milanês Maggi ®', unidade: 'colheres de sopa', carbs: 6 },
      { nome: 'Rocambole - Pullman ®', unidade: 'pedaços médios', carbs: 48 },
      { nome: 'Rocambole de brigadeiro diet', unidade: 'pedaços médios', carbs: 18 },
      { nome: 'Rocambole de doce de leite', unidade: 'pedaços médios', carbs: 45 },
      { nome: 'Rúcula', unidade: 'pratos de sobremesa', carbs: 2 },
      { nome: 'Ruffles ®', unidade: 'pacotes pequenos', carbs: 28 },
      { nome: 'Sagu em vinho', unidade: 'colheres de sopa', carbs: 6 },
      { nome: 'Sakê', unidade: 'doses', carbs: 3 },
      { nome: 'Sal', unidade: 'sachês', carbs: 0 },
      { nome: 'Salada de frutas', unidade: 'copos pequenos cheios', carbs: 19 },
      { nome: 'Salada de legumes', unidade: 'colheres de sopa cheias', carbs: 4 },
      { nome: 'Salame', unidade: 'fatias médias', carbs: 0 },
      { nome: 'Salame italiano', unidade: 'fatias', carbs: 0 },
      { nome: 'Salmão', unidade: 'filés pequenos', carbs: 0 },
      { nome: 'Salpicão de frango', unidade: 'colheres de sopa', carbs: 2 },
      { nome: 'Salsicha de frango', unidade: 'unidades médias', carbs: 2 },
      { nome: 'Salsicha tipo cachorro-quente', unidade: 'unidades', carbs: 0 },
      { nome: 'Salsichão', unidade: 'unidades médias', carbs: 0 },
      { nome: 'Sanduíche americano', unidade: 'unidades médias', carbs: 28 },
      { nome: 'Sanduíche de atum', unidade: 'unidades médias', carbs: 33 },
      { nome: 'Sanduíche de frango', unidade: 'unidades médias', carbs: 33 },
      { nome: 'Sanduíche natural', unidade: 'unidades médias', carbs: 29 },
      { nome: 'Sapoti', unidade: 'unidades pequenas', carbs: 16 },
      { nome: 'Sardinha em óleo', unidade: 'latas (drenado)', carbs: 0 },
      { nome: 'Sashimi de salmão', unidade: 'unidades médias', carbs: 0 },
      { nome: 'Seleta de legumes', unidade: 'colheres de sopa', carbs: 3 },
      { nome: 'Sidra', unidade: 'doses', carbs: 13 },
      { nome: 'Sonho', unidade: 'unidades', carbs: 22 },
      { nome: 'Soja', unidade: 'colheres de sopa', carbs: 2 },
      { nome: 'Sopa canja', unidade: 'conchas médias', carbs: 12 },
      { nome: 'Sopa creme de cebola - Knorr ®', unidade: 'conchas médias', carbs: 6 },
      { nome: 'Sopa creme de ervilha - Knorr ®', unidade: 'conchas médias', carbs: 5 },
      { nome: 'Sopa creme de galinha - Maggi ®', unidade: 'conchas médias', carbs: 4 },
      { nome: 'Sopa de ervilha', unidade: 'conchas médias', carbs: 20 },
      { nome: 'Sopa de ervilha com bacon', unidade: 'conchas médias', carbs: 20 },
      { nome: 'Sopa de feijão com macarrão', unidade: 'conchas médias', carbs: 30 },
      { nome: 'Sopa de legumes', unidade: 'conchas médias', carbs: 12 },
      { nome: 'Sopa de legumes com carne', unidade: 'conchas médias', carbs: 8 },
      { nome: 'Sopa de legumes/carne/macarrão', unidade: 'conchas médias', carbs: 16 },
      { nome: 'Sorvete light', unidade: 'bolas', carbs: 10 },
      { nome: 'Sorvete diet (média)', unidade: 'bolas médias', carbs: 10 },
      { nome: 'Sorvete (média)', unidade: 'bolas médias', carbs: 19 },
      { nome: 'Strudel de banana', unidade: 'fatias médias', carbs: 67 },
      { nome: 'Suco Ades comum (média) ®', unidade: 'copos duplos', carbs: 24 },
      { nome: 'Suco Ades Light (média) ®', unidade: 'copos duplos', carbs: 8 },
      { nome: 'Suco artificial comum', unidade: 'copos', carbs: 14 },
      { nome: 'Suco artificial diet', unidade: 'copos', carbs: 0 },
      { nome: 'Suco de abacaxi sem açúcar', unidade: 'copos', carbs: 26 },
      { nome: 'Suco de açaí com açúcar', unidade: 'copos duplos', carbs: 72 },
      { nome: 'Suco de acerola sem açúcar', unidade: 'copos', carbs: 5 },
      { nome: 'Suco de cajú sem açúcar', unidade: 'copos', carbs: 3 },
      { nome: 'Suco de laranja sem açúcar', unidade: 'copos', carbs: 21 },
      { nome: 'Suco de melancia sem açúcar', unidade: 'copos', carbs: 19 },
      { nome: 'Suco de morango sem açúcar', unidade: 'copos', carbs: 9 },
      { nome: 'Suco Mais ® (média)', unidade: 'copos', carbs: 26 },
      { nome: 'Suco Mais light ® (média)', unidade: 'copos', carbs: 8 },
      { nome: 'Suco Mc Laranja ®', unidade: 'copos', carbs: 34 },
      { nome: 'Suco Tang ®', unidade: 'copos', carbs: 21 },
      { nome: 'Suco tipo Maguary ® sem açúcar', unidade: 'copos', carbs: 3 },
      { nome: 'Sucrilhos®', unidade: 'copos pequenos cheios', carbs: 35 },
      { nome: 'Suflê de espinafre', unidade: 'colheres de sopa', carbs: 3 },
      { nome: 'Suflê de legumes', unidade: 'colheres de sopa', carbs: 5 },
      { nome: 'Suflê de queijo', unidade: 'pedaços pequenos', carbs: 4 },
      { nome: 'Sundae (Kibon) ®', unidade: 'unidades', carbs: 41 },
      { nome: 'Sundae (Mc Donald) ®', unidade: 'unidades', carbs: 46 },
      { nome: 'Sushi', unidade: 'unidades médias', carbs: 5 },
      { nome: 'Suspiro', unidade: 'unidades médias', carbs: 6 },
      { nome: 'Sustagem®', unidade: 'colheres de sopa', carbs: 12 },
      { nome: 'Tabule', unidade: 'colheres de sopa', carbs: 7 },
      { nome: 'Tapioca com queijo e coco', unidade: 'unidades médias', carbs: 31 },
      { nome: 'Tapioca seca', unidade: 'colheres de sopa', carbs: 31 },
      { nome: 'Toddynho', unidade: 'unidades', carbs: 30 },
      { nome: 'Toddynho fit', unidade: 'unidades', carbs: 26 },
      { nome: 'Toddy Light', unidade: 'colheres de sopa', carbs: 8 },
      { nome: 'Toddy original', unidade: 'colheres de sopa', carbs: 9 },
      { nome: 'Tofu', unidade: 'pedaços', carbs: 0 },
      { nome: 'Tomate', unidade: 'unidades pequenas', carbs: 2 },
      { nome: 'Torrada de pão francês', unidade: 'unidades pequenas', carbs: 5 },
      { nome: 'Torrada industrializada', unidade: 'unidades', carbs: 6 },
      { nome: 'Torta de Ch. cake com calda de frutas', unidade: 'fatias médias', carbs: 26 },
      { nome: 'Torta de frango', unidade: 'fatias médias', carbs: 15 },
      { nome: 'Torta de limão', unidade: 'fatias pequenas', carbs: 30 },
      { nome: 'Torta de liquidificador', unidade: 'fatias pequenas', carbs: 10 },
      { nome: 'Torta de maçã', unidade: 'fatias médias', carbs: 32 },
      { nome: 'Tremoço', unidade: 'colheres de sopa', carbs: 4 },
      { nome: 'Trigo para kibe', unidade: 'colheres de sopa', carbs: 11 },
      { nome: 'Trufa de chocolate', unidade: 'unidades grandes', carbs: 15 },
      { nome: 'Trufa de chocolate diet', unidade: 'unidades grandes', carbs: 13 },
      { nome: 'Tutu de feijão', unidade: 'colheres de sopa', carbs: 5 },
      { nome: 'Uva', unidade: '10 gomos médios', carbs: 14 },
      { nome: 'Uva passa', unidade: 'colheres de sopa cheias', carbs: 14 },
      { nome: 'Vaca atolada', unidade: 'conchas médias', carbs: 26 },
      { nome: 'Vagem', unidade: 'colheres de sopa', carbs: 1 },
      { nome: 'Vatapá', unidade: 'unidades', carbs: 9 },
      { nome: 'Vinho branco seco', unidade: 'taças', carbs: 0 },
      { nome: 'Vinho branco suave', unidade: 'taças', carbs: 15 },
      { nome: 'Vinho tinto seco', unidade: 'taças', carbs: 2 },
      { nome: 'Vinho tinto suave', unidade: 'taças', carbs: 15 },
      { nome: 'Vitamina com leite/fruta/açúcar', unidade: 'copos', carbs: 22 },
      { nome: 'Vitamina com leite/fruta/sem açúcar', unidade: 'copos', carbs: 15 },
      { nome: 'Vodka', unidade: 'medidas', carbs: 0 },
      { nome: 'Whisky', unidade: 'doses', carbs: 0 },
      { nome: 'Yakisoba', unidade: 'colheres de sopa', carbs: 4 },
      { nome: 'Yakult ®', unidade: 'frascos', carbs: 12 }
    ];
  }
}
